name: "Deploy site"

on:
  push:
    branches: [$default-branch]

  permissions:
    contents: read
    pages: write
    id-token: write

  workflow_dispatch:
    # Allow manually running workflow

environment:
  OUTPUT: _html

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lektor
        run: python -m pip install lektor

      - name: Build website
        run: lektor build -f webpack -O '${{ env.OUTPUT }}'

      #- name: Check for broken internal links
      #  uses: wjdp/htmltest-action@master
      #  with:
      #    path: ${{ env.OUTPUT }}
      #    config: .htmltest.yml
      #    skip_external: true
      #    log_level: 1

      - name: Deploy website
        run: lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          DEPLOY_USERNAME: chattanoogatabletennis
          DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
